// Original teaching slides; figures are generated by the companion programs.
const fs = require("fs");
const path = require("path");
const PptxGenJS = require("pptxgenjs");
const JSZip = require("jszip");
const pptx = new PptxGenJS();
pptx.layout = "LAYOUT_WIDE";
pptx.author = "work_superconductor";
pptx.subject = "Fixed-gap spin-singlet BdG and an Al cutoff benchmark";
pptx.title = "BdG超导理论与计算入门";
pptx.lang = "zh-CN";
pptx.theme = { headFontFace: "Microsoft YaHei", bodyFontFace: "Microsoft YaHei",
               lang: "zh-CN" };
const C = { ink:"183B3C", teal:"117E83", pale:"EDF5F2", paper:"F7F4ED",
            coral:"C55B43", gold:"857140", muted:"546968", white:"FFFFFF" };
const S = pptx.ShapeType;
const ROOT = path.resolve(__dirname, "..");
let number = 0;

function text(s, content, x, y, w, h, options={}) {
  s.addText(content, {x,y,w,h,fontFace:"Microsoft YaHei",fontSize:19,
    color:C.ink,margin:0,breakLine:false,valign:"top",
    ...options});
}
function shape(s,type,x,y,w,h,fill,line=fill) {
  s.addShape(type,{x,y,w,h,fill:{color:fill},line:{color:line,width:1}});
}
function page(title, english, notes, dark=false) {
  const s = pptx.addSlide(); number++;
  s.background={color:dark?C.ink:C.paper};
  text(s,String(number).padStart(2,"0"),.55,.38,.55,.45,
       {fontFace:"Cambria",fontSize:18,color:dark?"9EC9BE":C.teal});
  text(s,title,1.18,.35,11.55,.6,{fontSize:32,bold:true,color:dark?C.white:C.ink});
  text(s,english,1.18,1.03,11.2,.38,{fontSize:13,color:dark?"B1CECA":C.muted});
  text(s,"work_superconductor  /  BdG 第二课  /  2026-10-03",.6,7.05,11.9,.2,
       {fontSize:10,color:dark?"B1CECA":C.muted});
  s.addNotes(notes);
  return s;
}
function card(s,title,body,x,y,w=3.9,h=3.4,color=C.teal) {
  shape(s,S.rect,x,y,w,h,C.white);
  shape(s,S.rect,x,y,.09,h,color);
  text(s,title,x+.25,y+.3,w-.5,.65,{fontSize:23,bold:true,color});
  text(s,body,x+.25,y+1.15,w-.5,h-1.35,{fontSize:18,breakLine:false});
}
function banner(s,message,y=6.35,color=C.teal) {
  shape(s,S.rect,.6,y,12.1,.48,C.pale);
  text(s,message,.8,y+.08,11.7,.3,{fontSize:15,color,bold:true});
}
function formula(s,content,x=1,y=2.0,w=11.2,h=1.25,size=34) {
  shape(s,S.roundRect,x,y,w,h,C.pale);
  text(s,content,x+.3,y+.25,w-.6,h-.35,
       {fontFace:"Cambria Math",fontSize:size,align:"center",valign:"mid"});
}
function image(s,relative,x,y,w,h) {
  const p = path.join(ROOT,relative), buf=fs.readFileSync(p);
  const width=buf.readUInt32BE(16), height=buf.readUInt32BE(20);
  const scale=Math.min(w/width,h/height), iw=width*scale, ih=height*scale;
  s.addImage({path:p,x:x+(w-iw)/2,y:y+(h-ih)/2,w:iw,h:ih});
}
function table(s,rows,x=.65,y=1.85,w=12.0,h=3.7,widths) {
  s.addTable(rows,{x,y,w,h,fontFace:"Microsoft YaHei",fontSize:18,
    border:{type:"solid",color:"D8E2DC",pt:.8},margin:.12,
    color:C.ink,fill:C.white,valign:"middle",colW:widths,
    autoPage:false,bold:false,
    rowH:.58});
}
function chain(s,periodic,y,color=C.teal) {
  const xs=[1.25,2.4,3.55,4.7,5.85,7.0];
  xs.forEach((x,i)=>{
    if(i) s.addShape(S.line,{x:xs[i-1]+.22,y:y+.2,w:x-xs[i-1]-.22,h:0,
                            line:{color,width:2.5}});
    shape(s,S.ellipse,x,y,.4,.4,color);
    text(s,String(i+1),x-.03,y+.52,.5,.35,{fontSize:14,align:"center"});
  });
  if(periodic) {
    s.addShape(S.line,{x:1.45,y:y-.45,w:5.75,h:0,line:{color:C.coral,width:2}});
    s.addShape(S.line,{x:1.45,y:y-.45,w:0,h:.45,line:{color:C.coral,width:2}});
    s.addShape(S.line,{x:7.2,y:y-.45,w:0,h:.45,line:{color:C.coral,width:2}});
  }
}

let s = page("从 BCS 到 BdG", "Bogoliubov–de Gennes · spectrum, boundaries and LDOS",
  "这节课把上一课的 BCS 平均场转为可求本征值的 BdG 矩阵。第一课从相互作用得到温度依赖能隙，第二课暂时把能隙作为输入，研究激发与空间谱权重。强调教学模型和真实材料的区别。本课并未求解自洽、输运或拓扑不变量，也不能输出 Al 的临界温度。",true);
text(s,"超导理论与计算入门",.85,2.0,11,1,{fontSize:40,bold:true,color:C.white});
text(s,"固定均匀 s 波 · 自旋单态约化块",.9,3.2,11,.65,
     {fontSize:26,color:"B1CECA"});
text(s,"理论 → 代码 → 解析验证 → 物理解读",.9,4.65,10,.5,
     {fontSize:25,color:C.white});
shape(s,S.ellipse,11.4,4.35,.8,.8,C.teal);
shape(s,S.ellipse,10.25,4.35,.8,.8,C.coral);
text(s,"第二套学习包 / 30 页 / 代码与已执行 Notebook 配套",.9,6.15,11,.4,
     {fontSize:16,color:"B1CECA"});

s=page("先形成一个小闭环","Learning sequence",
  "建议分三次学习，每次先做预测再运行代码。第一步手算最小矩阵与相干因子，第二步搭建链并用解析谱校验，第三步学习局域态密度的投影权重。配套详细教程提供推导与答案，Notebook 的八格代码已实际执行。不要只看课件或只运行脚本，把基底、单位和局限写成自己的记录。");
card(s,"01  手推","2×2 块\n±E 与相干因子\n基底和单位",.65,2.0);
card(s,"02  搭建","正常态 h → BdG\nPBC 与 OBC\n解析与残差",4.72,2.0);
card(s,"03  解释","单自旋 LDOS\n尺寸和谱展宽\n杂质与局限",8.79,2.0,3.9,3.4,C.coral);
banner(s,"验收不是“画出能隙”，而是能解释每个符号、检查和近似。");

s=page("输入 Δ，而不是预测 Tc","Scope and non-goals",
  "本课的 Δ 是指定配对场而非计算结果。矩阵只有正常态跃迁、化学势、标量势和 on-site 单态配对，没有相互作用方程、温度自洽、磁场或自旋轨道耦合。开放边界和粒子–空穴结构都不等于拓扑。链是数值教学工具，不能据此断言真实一维体系有有限温长程超导序。");
card(s,"本课包含","均匀 s 波能谱\n边界与站波\n固定 Δ 的标量杂质",.85,2,5.6,3.7);
card(s,"本课不包含","自洽 Δ(T) 与 Tc\n材料 EPC 与输运\n拓扑不变量 / Majorana",6.75,2,5.6,3.7,C.coral);
banner(s,"BdG 是平均场描述方式，不是新的微观配对机制。");

s=page("每个参数先写单位","Symbols and units",
  "将跃迁能 J 作为统一能量单位，J=1。化学势、能隙、局部势和 LDOS 展宽均以 J 度量。格点间距取一，不代表具体材料长度。默认 N=48，矩阵是 96 维。eta 是可控谱展宽，不等于 QE 的 degauss，也没有从微观散射理论求得寿命。");
table(s,[["符号","英文概念","默认值 / 含义"],["J","hopping amplitude","1；能量单位"],
 ["μ","chemical potential","−0.5 J"],["Δ","pairing field","0.25 J；外部输入"],
 ["N","number of sites","48；矩阵维数 2N"],["η","Lorentzian broadening","0.04 J；绘图谱展宽"]],
 .65,1.7,12,4.3,[1.1,5.0,5.9]);
banner(s,"参数同名，不表示可直接替换成 DFT 输出。");

s=page("Nambu 基底决定矩阵含义","Reduced spin-singlet Nambu basis",
  "本课基底上半部分是自旋向上电子，下半部分是自旋向下空穴，组成自旋单态的约化块。不是给单个无自旋费米子写 on-site 配对。费米反对称性约束无自旋配对，Kitaev 链一般采用格点间 p 波配对。完整自旋 Nambu 空间还有相应另一块，比较文献必须先对齐基底和计数。");
card(s,"电子 sector","c₁↑  …  cN↑\n上半部分 N 个分量",.85,2,5.5,2.7);
card(s,"空穴 sector","c₁↓†  …  cN↓†\n下半部分 N 个分量",6.7,2,5.5,2.7,C.coral);
formula(s,"Ψ = (c₁↑ … cN↑ , c₁↓† … cN↓†)ᵀ",.85,5.1,11.5,1.05,27);

s=page("最小矩阵：电子与空穴混合","The 2 × 2 BdG block",
  "沿用第一课的配对负号约定。矩阵左上为 xi，右下为负 xi，非对角配对项必须互为复共轭以保持厄米性。整体负号可通过相位约定变化，不能仅看一个元素判定文献错误。Python 中本征矢储存在列，eigh 返回排序的实本征值。");
formula(s,"H(ξ) = [ ξ , −Δ ; −Δ* , −ξ ]",.8,2.05,11.6,1.25,36);
card(s,"正常态","ξ 是相对 μ 的能量\nΔ=0 时两块分离",.85,3.85,5.5,2.2);
card(s,"配对项","复数共轭不能省略\n本课负号与 BCS 一致",6.7,3.85,5.5,2.2,C.coral);

s=page("手推能谱，再做数值","Analytic eigenvalues",
  "先求行列式再用计算机。特征方程为 E 平方减 xi 平方减配对幅值平方等于零，得到正负准粒子谱。xi 为零时最低正能是配对幅值，而两个分支间距是两倍幅值。例子 xi=0.6、delta=0.25 给出正负 0.65。排序后正常态极限是正负绝对 xi。");
formula(s,"det(H − EI) = E² − ξ² − |Δ|² = 0",.8,1.9,11.6,1.2,32);
formula(s,"E± = ±√(ξ² + |Δ|²)",.8,3.45,11.6,1.2,40);
text(s,"ξ = 0.6 J，Δ = 0.25 J  →  E = ±0.65 J",1.15,5.2,11,.6,
     {fontSize:26,color:C.coral});
banner(s,"ξ=0 时正能为 |Δ|；正负分支的间距为 2|Δ|。");

s=page("开隙不是“多一条能带”","Quasiparticle spectrum",
  "图由配套 run_bdg.py 生成，并逐点与解析结果对比。实线是数值正负准粒子分支，空心点是解析结果。相干因子在下一页及 Notebook 中单独学习。加倍的 Nambu 描述不是新增加独立电子能带。观察到均匀能隙，只说明输入 delta 后这个平均场模型呈现相应激发谱，不能反推配对起源。");
image(s,"examples/03_bdg_uniform/results/momentum_spectrum.png",.7,1.65,11.9,4.6);
banner(s,"本征值与解析式的最大误差：8.88 × 10⁻¹⁶ J");

s=page("相干因子：权重随 ξ 转换","Coherence factors",
  "正能态的电子权重为二分之一乘一加 xi 除 E，空穴权重为互补量。远离费米面接近纯电子或空穴，在费米面各占一半。这是激发态的 Nambu 投影权重，不是实际电子数减半。数值测试直接比较本征矢电子分量与解析式，避免只比较本征值。");
formula(s,"|u|² = (1 + ξ/E)/2     |v|² = (1 − ξ/E)/2",.8,1.9,11.6,1.2,30);
card(s,"ξ ≫ |Δ|","正能态接近电子\n|u|² → 1",.7,3.55,3.8,2.35);
card(s,"ξ = 0","电子 / 空穴各一半\n|u|² = |v|² = 1/2",4.78,3.55,3.8,2.35,C.gold);
card(s,"ξ ≪ −|Δ|","正能态接近空穴\n|v|² → 1",8.86,3.55,3.8,2.35,C.coral);
banner(s,"ξ=0.6，Δ=0.25 → 正能电子权重约 0.961538");

s=page("先搭正常态链","Nearest-neighbor tight-binding model",
  "最近邻矩阵元为负 J，对角为局部势减化学势。先把正常态链写正确，再加入配对，错误更易定位。图只展示六个格点的示意，不表示实际计算只有六点。真实默认 N=48。代码限制 N 至少为三，避免两格点周期环重复键计数的约定歧义。");
formula(s,"hᵢⱼ = −J(δᵢ,ⱼ₊₁ + δᵢ,ⱼ₋₁) + (Uᵢ − μ)δᵢⱼ",.8,1.9,11.6,1.1,27);
chain(s,false,4.0);
text(s,"−J",2,3.45,1,.4,{fontSize:22,color:C.teal});
text(s,"Uᵢ − μ\non-site energy",8.2,3.8,3.8,1.1,{fontSize:25});
banner(s,"密集矩阵：约 O(N³) 时间、O(N²) 内存；练习 N=24–96。");

s=page("边界改变允许波数","Periodic vs open boundary conditions",
  "周期链额外连接首尾，允许波数为二 pi m 除 N。开放链是站波，波数为 pi m 除 N 加一。两种情况下均匀配对都可用正常态解析能量生成 BdG 谱。有限采样通常不会正好覆盖费米点，因此最低正能可能大于 delta。两个边界谱不同本身不是算法错误。");
chain(s,true,2.65);
text(s,"PBC：首尾相连",8.1,2.55,4,.5,{fontSize:23,bold:true});
chain(s,false,4.5);
text(s,"OBC：有限站波",8.1,4.4,4,.5,{fontSize:23,bold:true});
text(s,"PBC  kₘ=2πm/N     OBC  kₘ=πm/(N+1)",.9,5.7,11.5,.5,{fontSize:24});
banner(s,"ξₘ = −2J cos(kₘ) − μ；允许波数不同，最低正能可能高于 Δ。");

s=page("用 block 组装实空间矩阵","Real-space BdG Hamiltonian",
  "把 h 和配对对角矩阵 D 分别建立，再使用 NumPy block 组装四块。下右块是负 h 的复共轭，下左是负 D 的厄米共轭。这些共轭和负号不能随意删除。均匀 delta 时 D 与正常态变换相容，可逐模式与解析二乘二问题比较。");
formula(s,"D = diag(Δ₁, …, ΔN)",.9,1.8,11.5,1.0,30);
card(s,"左上 / 右上","h       /       −D",1.5,3.25,5.0,1.65);
card(s,"左下 / 右下","−D†     /       −h*",6.8,3.25,5.0,1.65,C.coral);
text(s,"矩阵维数 2N；本课通常令 Δᵢ = Δ",1.2,5.45,11,.55,{fontSize:26});

s=page("代码入口只有几行","A reproducible minimum example",
  "在案例目录运行，导入 bdg_chain 与解析谱。用 eigh 求本征对，比较排序的本征值。接着检查 H 乘 V 与 V 按列乘 E 的差，这直接判断本征方程。不要仅凭曲线美观或出现能隙判断正确。详细教程给出环境安装命令，Notebook 已按顺序执行。");
shape(s,S.roundRect,.8,1.85,11.7,3.95,C.ink);
text(s,"H = bdg_chain(48, mu=-0.5, delta=0.25)\n"+
 "e, v = np.linalg.eigh(H)\n"+
 "ref = analytic_chain_spectrum(48, mu=-0.5)\n"+
 "assert np.max(abs(e - ref)) < 1e-12\n"+
 "residual = np.max(abs(H @ v - v * e))",
 1.15,2.2,11.0,3.0,{fontFace:"Consolas",fontSize:23,color:C.white,paraSpaceAfter:14});
banner(s,"同目录 bdg.py / test_bdg.py / run_bdg.py / 已执行 Notebook");

s=page("两种边界，都要对照解析","Numerical vs analytic chain spectra",
  "解析比较是独立基准，不是把同一算法的输出重复画一遍。PBC 与 OBC 各自比较自己的允许波数。对默认案例，两种最大误差约一点七八乘十的负十五次方，接近双精度舍入量级。不同平台的最后一位可能不同，因此测试使用合理容差。");
image(s,"examples/03_bdg_uniform/results/chain_spectrum.png",.7,1.65,11.9,4.7);
banner(s,"PBC 与 OBC 的最大解析误差均约 1.78 × 10⁻¹⁵ J");

s=page("三个检查，约束物理解读","Hermiticity, residuals and completeness",
  "数值正确性分层检查。第一看矩阵是否厄米，第二看本征方程残差与正交归一，第三看电子投影完备性。仅有正负能谱成对不足以保证实现正确，因为错误的块也可能巧合成对。本课单自旋电子投影每格点求和应为一，不是二。");
card(s,"矩阵","H = H†\n错误常在共轭或负号",.7,2,3.8,3.4);
card(s,"本征对","HV = V diag(E)\nV†V = I",4.78,2,3.8,3.4,C.gold);
card(s,"电子权重","Σν |uᵢν|² = 1\n单自旋、每格点",8.86,2,3.8,3.4,C.coral);
banner(s,"额外检查 ±E 成对、Δ=0 极限、整体相位不变性。");

s=page("粒子–空穴算符随基底改变","Particle–hole structure in the reduced block",
  "这里必须强调约化单态块的表示。反幺正 C 为 tau y 乘复共轭，平方负一。这不代表任何完整 BdG 描述都使用相同平方值。无自旋 tau x K 不能直接放进本课的矩阵检查。改变 Nambu 基底时 H 和对称算符必须一起变换；数值测试包含空间变化的复 delta。");
formula(s,"C = (τᵧ ⊗ I) K     C² = −1",.8,1.9,11.6,1.2,36);
formula(s,[{text:"U"},{text:"C",options:{subscript:true}},
 {text:" H* U"},{text:"C",options:{subscript:true}},{text:"† = −H"}],
 .8,3.45,11.6,1.2,36);
text(s,"适用本课自旋单态约化块；不要混用无自旋 τₓK。",1.0,5.3,11.3,.7,
     {fontSize:24,color:C.coral,bold:true});

s=page("LDOS：只看电子投影","Local density of states",
  "本课选择全部二 N 本征态求和一次的电子投影公式，洛伦兹核积分为一。eta 是绘图参数，不能自动解释成散射寿命。有限能量窗口会漏掉尾部，积分小于一不一定有错误。单自旋电子 LDOS 在正负能不必对称，即使总 BdG 本征谱成对。");
formula(s,[{text:"ρ"},{text:"↑",options:{subscript:true}},
 {text:"(i,E) = Σ"},{text:"ν",options:{subscript:true}},
 {text:" |u"},{text:"iν",options:{subscript:true}},
 {text:"|² L"},{text:"η",options:{subscript:true}},
 {text:"(E − E"},{text:"ν",options:{subscript:true}},{text:")"}],
 .8,1.85,11.6,1.2,32);
formula(s,[{text:"L"},{text:"η",options:{subscript:true}},
 {text:"(x) = η / [π(x² + η²)]"}],.8,3.4,11.6,1.1,31);
text(s,"单自旋  /  全部 2N 态一次  /  无限窗积分为 1",1.0,5.25,11.4,.8,
     {fontSize:25,bold:true});

s=page("两种求和公式，必须二选一","Avoid Nambu double counting",
  "全谱电子投影与只对正能态求和的 u 和 v 公式等价，在本课无零模并满足对应配对结构时成立。两种不能同时用，否则重复计数。完整两自旋 DOS 的二倍因子只在本课自旋对称条件下适用，不能乘进单自旋权重检查。若有零模，需要单独处理而不是机械筛掉零能。");
card(s,"方式 A：全谱","全部 2N 个态\n仅用电子分量 |u|²\n本课代码采用此式",.8,2,5.6,3.7);
card(s,"方式 B：正能","仅 Eν>0\n|u|² 在 +Eν\n|v|² 在 −Eν",6.7,2,5.6,3.7,C.coral);
banner(s,"全谱公式后再加负能伙伴，会重复计数。");

s=page("边界改变局部谱权重","Edge vs center LDOS",
  "开放边界的站波使边缘与中心局部权重不同，不能只看全局本征值理解空间结构。图的 eta 固定为零点零四，gap 内小尾部来自洛伦兹展宽，不对应新本征态。默认最低正能约零点二五六，大于输入零点二五，属于离散波数未正好到费米点的有限尺寸效应。");
image(s,"examples/03_bdg_uniform/results/boundary_ldos.png",.7,1.6,11.9,4.75);
banner(s,"中心有限窗积分约 0.986922；不要人为归一化掩盖尾部。");

s=page("尺寸与展宽分开改变","Finite size and spectral broadening",
  "左图固定展宽改变尺寸，右图固定尺寸改变展宽。两个变量一次只能改变一个，避免把平滑的原因误判为收敛。较小 eta 暴露有限尺寸离散峰，较大 eta 可把 gap 曲线填平。最低正能随 N 未必严格单调，因为波数与费米点的匹配会变化。");
image(s,"examples/03_bdg_uniform/results/size_and_broadening.png",.7,1.6,11.9,4.75);
banner(s,"先固定 η 扫 N，再固定 N 扫 η；看原始本征值而非只看曲线。");

s=page("标量杂质：改变权重，不造零模","Nonmagnetic scalar impurity",
  "中心自旋无关势为二 J，delta 仍固定且均匀。实对称正常态 h 可对角化，而 delta 单位矩阵保持形式，所以每个正常态能级 epsilon 仍给出正负根号 epsilon 平方加 delta 平方。这个模型中不存在绝对能量小于 delta 的本征值，也没有磁性 Shiba 或 Majorana 零模。");
image(s,"examples/03_bdg_uniform/results/impurity_ldos.png",.7,1.6,11.9,4.75);
banner(s,"U=2J 时最低正能约 0.254064J ≥ |Δ|；Δ 未自洽更新。");

s=page("不要从一个谱峰跳到机制","What the model cannot establish",
  "明确禁止几种常见推断。开放边界不等于拓扑，粒子–空穴结构是 BdG 描述的一部分，也不等于 Majorana 证据。gap 内曲线尾部需要先看本征值和展宽。标量杂质与磁交换不同，本课不构成自洽无序体系 Anderson 定理的证明。微观机制需要额外实验或相互作用计算证据。");
card(s,"开放边界","不自动产生拓扑\n不自动产生 Majorana",.7,2,3.8,3.7,C.coral);
card(s,"谱峰 / 尾部","先检查 Eν、η 和 N\n不凭画图判断束缚态",4.78,2,3.8,3.7,C.gold);
card(s,"输入 Δ","证明本模型有隙\n不能反推配对媒介",8.86,2,3.8,3.7);
banner(s,"YSR 态需要磁性模型；拓扑结论需要额外不变量与稳定性分析。");

s=page("按同一流程保存每次实验","Reproducibility workflow",
  "学习计算要留输入、版本、结果和判断依据。先固定模型和单位，再运行测试与结果脚本，把 Notebook 实际执行输出存档。改变参数时使用独立记录，说明只变了什么。最后写出能证实与不能证实的事项。脚本成功只是技术运行完成，学习验收还包括独立推导和解释。");
["模型与单位","参数与版本","解析 / 残差","图与 CSV","解释与局限"].forEach((label,i)=>{
  shape(s,S.roundRect,.8+i*2.48,2.55,2.2,1.1,i===4?C.coral:C.teal);
  text(s,label,.93+i*2.48,2.85,1.95,.5,{fontSize:19,color:C.white,align:"center"});
});
text(s,"python -m unittest test_bdg.py -v\npython run_bdg.py\npython build_notebook.py",
 1.1,4.4,11,1.6,{fontFace:"Consolas",fontSize:23,paraSpaceAfter:12});
banner(s,"Notebook 重建脚本会覆盖教学文件；个人练习另存独立 Notebook。");

s=page("本课实际通过了哪些检查","Verified numerical benchmarks",
  "本页列的是已执行结果，不是预期值。十一项单元测试覆盖解析谱、相干因子、边界、对称结构、正常态和全局相位极限、权重与非法输入。Notebook 八格已执行。数值误差接近双精度舍入水平；这些只验证指定模型实现，不能跨越到真实材料机制结论。");
card(s,"11","自动测试已通过\n解析谱与 LDOS 计数",.7,2,3.8,3.55);
card(s,"8","Notebook 代码单元\n逐格执行无错误",4.78,2,3.8,3.55,C.gold);
card(s,"≈ 10⁻¹⁵","解析谱误差量级\n双精度数值验证",8.86,2,3.8,3.55,C.coral);
banner(s,"详见 examples/03_bdg_uniform/results/validation.json");

s=page("独立练习，而不是继续堆概念","Exercises with clear acceptance criteria",
  "这页练习在详细教程有参考答案，但建议先独立完成。正常态极限检查谱，化学势变化检查电子投影对称性，尺寸和展宽分开扫描检查误差来源。最后解释标量杂质不造 gap 内态和不能输出 Tc 的原因。完成一页记录比增加十个未经验证的复杂功能更有学习价值。");
table(s,[["练习","你需要说明"],["Δ → 0","正常态块与 ±|ξ|"],
 ["μ=-0.5 → 0","能谱对称与电子 LDOS 对称的区别"],
 ["固定 η 扫 N；固定 N 扫 η","离散化、谱尾部、最低正能"],
 ["标量杂质 U=2","为何 |E|≥|Δ|"],
 ["能否输出 Al 的 Tc？","缺少自洽与材料 EPC"]],
 .65,1.8,12,4.15,[4.2,7.8]);
banner(s,"交付一页记录：基底 + 参数 + 推导 + 三项误差 + 局限。");

s=page("模型与材料是两条相连的路线","BdG vs first-principles superconductivity",
  "左边 BdG 输入配对场研究空间谱，右边材料计算从结构、电子态和声子得到电子–声子耦合，之后求 Eliashberg。Al 截断能扫描是材料数值准备，不是 BdG 对真实 Al 的预测。两条路线可在低能模型和材料参数化阶段联系，但需要明确映射与近似，不能把同名字母直接代入。");
card(s,"模型路线","BCS → 固定 Δ 的 BdG\n→ 自洽空间问题\n基底与权重是关键",.8,2,5.6,3.8);
card(s,"材料路线","DFT → DFPT → EPC\n→ Eliashberg\n网格与展宽是关键",6.7,2,5.6,3.8,C.coral);
banner(s,"两边都要求收敛与验证；本次尚未完成材料 Tc 预测。");

s=page("Al：真实集群单变量扫描","Al cutoff scan · Slurm JobID 313292",
  "本次在 IQ 集群通过 HostBridge 路径完成五组 SCF，四 MPI，状态 completed，退出零，耗时十八秒。固定 ecutrho 六百四十 Ry、八立方 k 网格、mv 展宽零点零二 Ry 和结构。只改变 ecutwfc。原始日志与输入哈希已回收；赝势不在仓库再分发。");
table(s,[["ecutwfc / Ry","E / Ry","|ΔE| / meV·atom⁻¹"],
 ["30","−39.50300654","0.793348"],["40","−39.50303898","0.351979"],
 ["50","−39.50305397","0.148030"],["60","−39.50305990","0.067348"],
 ["80","−39.50306485","0（有限参考）"]],.7,1.75,11.9,4.3,[3.0,4.7,4.2]);
banner(s,"固定 ecutrho=640 Ry，k=8³，mv degauss=0.02 Ry；每胞一个 Al。");

s=page("总能阈值 ≠ 声子或 Tc 收敛","Finite-reference energy criterion",
  "默认目标一 meV 每原子，最低已测试点三十 Ry 满足与八十 Ry 的差值及所有更高测试点条件。但八十 Ry 不是真值，ecutrho、k 网格和展宽仍未独立验证。图同时显示应力为独立观测量。本次固定几何压力约负八 kbar，不能声称零压平衡结构。较严格零点一 meV 目标则候选为六十 Ry。");
image(s,"examples/04_qe_al_cutoff/results/cutoff_convergence.png",.7,1.6,11.9,4.75);
banner(s,"30 Ry 达到 1 meV/原子有限参考目标；尚未验证 k、展宽、ecutrho 和声子。");

s=page("下一步：先验收，再分流","Next steps and dependency order",
  "优先完成 BdG 独立练习。模型路线的下一阶段要推导相互作用、温度和填充约束，再写自洽循环与混合、残差和自由能判断。材料路线先测试 k 网格与展宽，再检查 ecutrho 和几何，随后有限 q 声子与 EPC。文献路线只选一个原始图表，明确参数和误差，不把本次解析基准标成原论文完全复现。");
card(s,"理论 / 模型","独立推导与参数扫描\n→ 自洽 BdG 的设计\n→ 空间非均匀练习",.7,2,3.8,3.65);
card(s,"材料 / 集群","k 网格与展宽\n→ ecutrho、几何、声子\n→ EPC / Eliashberg",4.78,2,3.8,3.65,C.gold);
card(s,"文献 / 复现","一篇原始论文\n一个明确图号\n参数、原图与误差",8.86,2,3.8,3.65,C.coral);
banner(s,"一次只推进一个可验收问题；后续计划不写成已完成。");

s=page("保持基底、误差和证据清楚","Sources and takeaways",
  "本课文字、代码、图和课件为原创教学材料，不直接复制未获授权的教材章节或讲义。来源页指向 BCS 原始论文、Kwant 官方教程和 QE、EPW 官方文档。仓库已有 MIT 开放教材继续保留自己的许可与来源记录。本课可作为后续独立文献复现的数值基础，但没有完成任何原始研究图表的定量对比。",true);
text(s,"先写基底，再写矩阵。\n先做验证，再解释谱峰。\n先完成收敛，再讨论材料 Tc。",
 .9,1.95,11.5,2.35,{fontSize:29,color:C.white,paraSpaceAfter:15});
text(s,"BCS: doi.org/10.1103/PhysRev.108.1175\n"+
 "Kwant: kwant-project.org/doc/1/tutorial/superconductors\n"+
 "QE: quantum-espresso.org/Doc/INPUT_PW.html\n"+
 "EPW: docs.epw-code.org/tutorials/tutorial_04/index.html",
 .95,4.65,11.4,1.65,{fontSize:16,color:"B1CECA",paraSpaceAfter:8});

(async()=>{
  if(number!==30) throw Error("Expected 30 slides");
  const file=path.join(__dirname,"BdG超导理论与计算入门.pptx");
  await pptx.writeFile({fileName:file});
  // Omit the optional registry that PptxGenJS places out of schema order.
  // Per-slide notes parts and their relationships remain intact.
  const zip=await JSZip.loadAsync(fs.readFileSync(file));
  const xml=await zip.file("ppt/presentation.xml").async("string");
  zip.file("ppt/presentation.xml",xml.replace(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/,""));
  fs.writeFileSync(file,await zip.generateAsync({type:"nodebuffer",compression:"DEFLATE"}));
  console.log("Built 30 slides with 30 detailed speaker notes: "+file);
})().catch(error=>{console.error(error);process.exit(1);});
