// Original bilingual teaching deck. Figures come from the paired BCS example.
const pptxgen = require("pptxgenjs");
const path = require("node:path");
const fs = require("node:fs");
const JSZip = require("jszip");
const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE";
pptx.author = "work_superconductor learning project";
pptx.subject = "BCS theory, numerical validation and QE cluster smoke test";
pptx.title = "BCS超导理论与计算入门";
pptx.company = "LRH123LRH123/work_superconductor";
pptx.lang = "zh-CN";
pptx.theme = { headFontFace: "Microsoft YaHei", bodyFontFace: "Microsoft YaHei", lang: "zh-CN" };

const C = { ink: "183C3C", teal: "087F8C", cream: "F6F2E9", white: "FFFFFF",
  muted: "506D6C", coral: "C65B35", pale: "E1EEEB", soft: "EADBC7" };
const fig = path.join(__dirname, "../examples/01_bcs_gap/results");
const stats = JSON.parse(fs.readFileSync(path.join(fig, "validation.json"), "utf8"));
const total = 33;

function text(s, value, x, y, w, h, opts = {}) {
  s.addText(value, { x, y, w, h, fontFace: "Microsoft YaHei", fontSize: 21,
    color: C.ink, margin: 0, breakLine: false, valign: "mid", ...opts });
}
function rect(s, x, y, w, h, fill = C.white) {
  s.addShape(pptx.ShapeType.rect, { x, y, w, h, line: { color: fill, transparency: 100 },
    fill: { color: fill } });
}
function circle(s, x, y, size, fill = C.teal) {
  s.addShape(pptx.ShapeType.ellipse, { x, y, w: size, h: size,
    line: { color: fill }, fill: { color: fill } });
}
function line(s, x, y, w, h, color = C.teal, width = 2) {
  s.addShape(pptx.ShapeType.line, { x, y, w, h, line: { color, width } });
}
function make(title, section, note, dark = false) {
  const s = pptx.addSlide();
  s.background = { color: dark ? C.ink : C.cream };
  text(s, section.toUpperCase(), .65, .36, 11.7, .26,
       { fontSize: 11, color: dark ? "A6CECA" : C.teal, charSpacing: 2 });
  text(s, title, .65, .87, 12.0, .77,
       { fontSize: 34, bold: true, color: dark ? C.white : C.ink });
  text(s, "超导理论 × 计算 × 验证  |  2026-10-03", .65, 7.03, 10.7, .22,
       { fontSize: 10, color: dark ? "A6CECA" : C.muted });
  text(s, String(pptx._slides.length).padStart(2, "0") + " / " + total,
       11.88, 7.00, .8, .25, { fontSize: 11, align: "right",
         color: dark ? "A6CECA" : C.muted });
  s.addNotes(note);
  return s;
}
function panel(s, title, body, x, y, w, h, fill = C.white) {
  rect(s, x, y, w, h, fill);
  text(s, title, x + .23, y + .22, w - .46, .55,
       { fontSize: 22, bold: true, color: C.teal });
  text(s, body, x + .23, y + .95, w - .46, h - 1.16,
       { fontSize: 20, valign: "top", paraSpaceAfterPt: 9 });
}
function formula(s, value, y, caption = "") {
  rect(s, .65, y, 12.02, 1.24, C.pale);
  text(s, value, .95, y + .18, 11.4, .68,
       { fontFace: "Cambria Math", fontSize: 29, align: "center" });
  if (caption) text(s, caption, .98, y + .89, 11.3, .23,
    { fontSize: 12, color: C.muted, align: "center" });
}
function steps(s, items, y = 2.3) {
  const w = (12.02 - .25 * (items.length - 1)) / items.length;
  items.forEach((item, i) => {
    const x = .65 + i * (w + .25);
    rect(s, x, y, w, 2.8, i % 2 ? C.pale : C.white);
    circle(s, x + .22, y + .22, .52);
    text(s, String(i + 1), x + .22, y + .23, .52, .48,
         { fontSize: 21, color: C.white, align: "center", bold: true });
    text(s, item[0], x + .23, y + .98, w - .46, .55, { fontSize: 22, bold: true });
    text(s, item[1], x + .23, y + 1.77, w - .46, .8,
         { fontSize: 17, valign: "top" });
  });
}
function image(s, name, x, y, w, h) {
  const file = path.join(fig, name);
  const png = fs.readFileSync(file);
  const ratio = png.readUInt32BE(16) / png.readUInt32BE(20);
  const width = Math.min(w, h * ratio);
  const height = width / ratio;
  s.addImage({ path: file, x: x + (w - width) / 2, y: y + (h - height) / 2,
    w: width, h: height, altText: name + "; generated by run_bcs.py" });
}
function table(s, rows, x = .65, y = 2.02, w = 12.02, colW = [2.9, 3.6, 5.52]) {
  s.addTable(rows.map((row, i) => row.map(cell => ({
    text: cell, options: { fill: { color: i === 0 ? C.teal : i % 2 ? C.white : C.pale },
      color: i === 0 ? C.white : C.ink, bold: i === 0 }
  }))), { x, y, w, colW, border: { color: C.cream, pt: 2 },
    fontFace: "Microsoft YaHei", fontSize: 18, margin: .16,
    rowH: .57, autoPage: false, valign: "middle", color: C.ink });
}

// 01: the cover uses a native pairing motif and a generated result.
{
 const s = make("BCS 超导理论与计算入门", "Learning module 01",
  "本课不是研究结论报告，而是从模型推导到数值验证，再到第一性原理基础测试的入门课程。建议分三次学习：推导、代码、验证。阅读同名中文教程，运行 Notebook，最后解释每张图。所有中文内容和配套程序为本仓库编写；MIT OCW 原教材另外保存并按其许可注明归属。", true);
 text(s, "从一个可验证的模型出发", .7, 2.12, 7.3, .7,
      { color: C.white, fontSize: 28 });
 text(s, "Theory → Code → Checks → Materials", .7, 3.07, 7.3, .55,
      { fontFace: "Cambria", color: "A6CECA", fontSize: 24 });
 text(s, "中文推导 · 可运行 Python · 交互练习\n真实集群测试 · 原始记录 · 开放教材", .7, 4.05, 7.15, 1.1,
      { color: C.white, fontSize: 22, paraSpaceAfterPt: 12 });
 circle(s, 9.08, 2.2, 2.75, C.teal);
 text(s, "Δ", 9.12, 2.34, 2.67, 2.07, { fontFace: "Cambria Math",
       color: C.white, fontSize: 97, align: "center" });
 text(s, "能隙只是起点，验证才是桥梁", .7, 6.2, 11.8, .42,
      { color: "A6CECA", fontSize: 19 });
}
{
 const s=make("完成本课后，你应能解释什么？","Learning outcomes",
  "验收不是背出3.53，而是知道该值来自弱耦合极限，并能独立求解方程。学习者应知道输入是有效配对参数，输出是模型能隙和配对温度。真实材料测试只有常态SCF与Γ点声子和ASR后处理，没有EPC或材料Tc。");
 steps(s,[["推导","从 Hamiltonian 到能隙方程"],["计算","扫描 Δ(T)、Tc 和 DOS"],["验证","解析极限、残差与单位"],["迁移","区分 DFT、DFPT 与 EPC"]]);
 text(s,"验收方式：讲清一条公式，运行一段代码，解释一项误差。",.7,5.77,11.8,.8,{fontSize:25});
}
{
 const s=make("模型计算与材料计算是两条相连的线","Big picture",
  "BCS模型提供可解析的训练场。第一性原理路线提供真实电子态、声子和矩阵元。关联材料还需要相互作用模型和多体方法。本课不把声子路线当成所有超导的通用解释，也不把材料分类、序参量对称性和配对机制混为一谈。");
 panel(s,"本课：模型基准","有效吸引 g、截止 Ec\n→ 能隙方程\n→ Δ(T)、模型 Tc、DOS",.65,2.0,3.8,3.57);
 panel(s,"材料：声子路线","DFT → DFPT → EPC\n→ α²F 或各向异性核\n→ Eliashberg 与收敛",4.76,2.0,3.8,3.57,C.pale);
 panel(s,"材料：关联路线","Wannier / Hubbard\n→ 顶角、涨落与配对核\n→ 多体方法与误差",8.87,2.0,3.8,3.57);
 text(s,"本次连接点：Al 的常态 SCF + Γ 点 DFPT 冒烟测试。",.75,6.08,11.6,.48,{fontSize:23,color:C.coral});
}
{
 const s=make("先把假设写清楚","Model assumptions",
  "本模型取均匀各向同性s波、常单自旋DOS、对称能量截止和平均场。有效吸引没有在代码中由声子计算得到。没有多带、强关联、磁场、涡旋、相位涨落和BKT。符号Δ在该均匀无流无破对模型中对应最小正准粒子能量；一般材料不能如此简单等同。");
 panel(s,"均匀各向同性","Δ 与空间、动量无关\n选规范后可取实非负",.65,2.0,5.83,1.99);
 panel(s,"常 DOS 与对称截止","N₀ 为单自旋 DOS\n只在 |ξ| < Ec 内配对",6.84,2.0,5.83,1.99,C.pale);
 panel(s,"平均场 Mean Field","以配对平均值替代涨落\n不含涡旋与相位无序",.65,4.31,5.83,1.99,C.pale);
 panel(s,"不是材料预测","g 与 Ec 是假设输入\n不能从结果反证机制",6.84,4.31,5.83,1.99);
}
{
 const s=make("符号表：尤其留意单自旋 DOS","Notation",
  "N0与V的体积或格点归一化必须配套。如果资料使用双自旋总DOS，应先除以2得到这里的N0。ξ是相对化学势的常态能量。Ec是配对窗口，不是DFT平面波动能截止。程序temperature表示kBT/Ec，而不是开尔文。");
 table(s,[["符号","英文概念","本课约定"],["ξ = ε − μ","Relative energy","相对化学势的常态能量"],["N₀","Single-spin DOS","若给双自旋总 DOS，N₀ = Ntotal / 2"],["V > 0","Attraction magnitude","吸引项前显式写负号"],["g = N₀V","Coupling","无量纲有效吸引"],["Ec","Pairing cutoff","配对窗口能标，不是 ecutwfc"],["Δ、kBT","Gap / Thermal energy","无量纲化后 d = Δ/Ec，t = kBT/Ec"]]);
}
{
 const s=make("Cooper 配对：反向动量、相反自旋","Physical picture",
  "图只是动量空间配对示意，不代表电子沿圆轨道运动。约化模型挑选时间反演相关的k↑与−k↓配对，形成自旋单态s波通道。Cooper问题和BCS多体相干态不是同一个问题。有限密度体系的宏观相位相干也不自动由二体束缚证明。");
 s.addShape(pptx.ShapeType.ellipse,{x:1.4,y:2.04,w:4.0,h:4.0,
  line:{color:C.teal,width:3},fill:{color:C.cream,transparency:100}});
 s.addShape(pptx.ShapeType.line,{x:1.75,y:2.5,w:3.3,h:3.1,flipV:true,
  line:{color:C.muted,width:1.4}});
 circle(s,4.36,2.3,.5,C.coral);circle(s,1.84,5.09,.5,C.teal);
 text(s,"k ↑",4.81,2.04,1.1,.5,{fontSize:25,color:C.coral});
 text(s,"−k ↓",.87,5.67,1.6,.5,{fontSize:25,color:C.teal});
 text(s,"费米面附近的配对示意",1.3,6.3,4.5,.4,{fontSize:17,color:C.muted});
 panel(s,"成对算符","Bₖ = c₋ₖ↓ cₖ↑\n湮灭一对电子。\n\n〈Bₖ〉是配对异常平均值，\n不是普通电子占据。",6.58,2.2,6.08,3.95,C.pale);
}
{
 const s=make("约化 BCS Hamiltonian","Reduced Hamiltonian",
  "完整公式和求和归一化见中文教程。这里用B算符减少投影上的上标负担。V为正的吸引大小，负号显式位于相互作用前。k,k′都限定在配对窗口。电子动能使用ξ=ε−μ。这个模型并未显式计算声子。");
 formula(s,"H = Σₖσ ξₖ c†ₖσ cₖσ − V Σₖₖ′ B†ₖ Bₖ′",2.0,"Bₖ = c₋ₖ↓ cₖ↑；求和归一化吸收入 V");
 steps(s,[["常态能量","ξₖ 描述费米面附近状态"],["有效吸引","配对从 k′ 散射到 k"],["作用窗口","|ξₖ|、|ξₖ′| < Ec"]],3.7);
}
{
 const s=make("平均场：把多体问题变成二次型","Mean-field decoupling",
  "把B写成平均值加涨落。B†B保留线性涨落项，舍去二阶涨落项。定义Δ=VΣ〈B〉，得到配对二次型和|Δ|²/V常数。该常数在能谱问题中不改变本征值，但自由能比较时不可丢。平均场近似不是严格求解强关联体系。");
 steps(s,[["定义","Δ = V Σₖ〈Bₖ〉"],["分解","B = 〈B〉+ δB"],["舍去","δB† δB 二阶涨落"]],2.02);
 formula(s,"HMF = H₀ − Σₖ(ΔB†ₖ + Δ*Bₖ) + |Δ|²/V",5.32,"常数项必须保留，才能正确比较自由能。");
}
{
 const s=make("Nambu 表象：电子与空穴一起写","Nambu spinor",
  "使用Ψ=(c_k↑,c†_−k↓)^T。按前页Δ定义，矩阵的非对角元为−Δ和−Δ*。其他资料可能以不同相位约定写成+Δ，但能谱不变。±E是Nambu表象的结构，不能据此再把物理电子态数额外乘以2。");
 panel(s,"Nambu spinor","Ψₖ = ( cₖ↑ , c†₋ₖ↓ )ᵀ\n\n电子/空穴基底共同描述配对。",.65,2.1,5.5,3.97);
 rect(s,6.49,2.1,6.18,3.97,C.pale);
 text(s,"hₖ",6.87,2.5,1.1,.65,{fontFace:"Cambria Math",fontSize:36});
 text(s,"ξₖ        −Δ\n−Δ*      −ξₖ",8.02,2.65,3.9,2.0,{fontFace:"Cambria Math",fontSize:39,align:"center"});
 line(s,7.79,2.59,0,2.14);line(s,12.08,2.59,0,2.14);
 text(s,"非对角项把电子与空穴混合。",6.91,5.15,5.4,.53,{fontSize:20});
}
{
 const s=make("准粒子谱：从 2 × 2 矩阵直接得到","Quasiparticle spectrum",
  "由det(h−EI)=0得到E²=ξ²+|Δ|²。在ξ=0最小正能量为|Δ|。这描述均匀、无流、无破对的各向同性模型，不应把它推成所有超导态的结论。练习是用numpy.linalg.eigvalsh逐点检验解析式。");
 formula(s,"E± = ±√(ξ² + |Δ|²)",2.0);
 panel(s,"在费米面 ξ = 0","最小正准粒子能量为 |Δ|\n粒子–空穴两支对称。",.65,3.67,5.83,2.59);
 panel(s,"动手验证","构造 [[ξ, −Δ], [−Δ, −ξ]]\n对比 eigvalsh 与解析式。",6.84,3.67,5.83,2.59,C.pale);
}
{
 const s=make("相干因子：准粒子不是纯电子","Coherence factors",
  "实Δ且采用一致Bogoliubov变换约定时，u²=(1+ξ/E)/2，v²=(1−ξ/E)/2，uv=Δ/(2E)。在ξ=0，u²=v²=1/2。在远离费米面时恢复接近电子或空穴特征。不要把Nambu双分支当双倍DOS。");
 formula(s,"uₖ² = (1 + ξₖ/Eₖ)/2     vₖ² = (1 − ξₖ/Eₖ)/2",2.0);
 panel(s,"费米面附近","ξ → 0：u² = v² = 1/2\n电子与空穴强烈混合。",.65,3.67,5.83,2.59);
 panel(s,"远离费米面","|ξ| ≫ |Δ|：一种成分占主导\n逐渐接近常态特征。",6.84,3.67,5.83,2.59,C.pale);
}
{
 const s=make("自洽：输入 Δ，也必须输出同一个 Δ","Self consistency",
  "有限温度的异常平均值为Δ/(2E)tanh(E/2kBT)。代回Δ定义就形成自洽方程。原始方程始终有Δ=0解，非零配对支路需要额外处理。本代码没有盲目从零开始固定点迭代，而是用非零支路残差括区间求根。");
 steps(s,[["给出 Δ","由它确定 Eₖ"],["热占据","1 − 2f(E) = tanh(E/2kBT)"],["计算平均值","〈Bₖ〉= Δ tanh(Eₖ/2kBT)/(2Eₖ)"],["闭合","Δ = V Σₖ〈Bₖ〉"]],2.1);
 text(s,"原始方程总有 Δ = 0；下一步的除法只适用于非零分支。",.75,5.64,11.6,.89,{fontSize:24,color:C.coral});
}
{
 const s=make("求和变积分：因子 2 在这里抵消","DOS normalization",
  "对k求和转成单自旋DOS N0在−Ec到Ec的积分。分母有2E，核是偶函数，正负区间带来的2抵消分母2。若使用总双自旋DOS则须先取Ntotal/2。详细LaTeX公式见配套教程，不要凭记忆添加自旋因子。");
 formula(s,"1 = VN₀ ∫₋Ecᴱc [tanh(E/2kBT)/(2E)] dξ",2.0);
 text(s,"偶函数积分 × 2  与  分母 2  相互抵消",.75,3.63,11.6,.61,{fontSize:26,align:"center",color:C.coral});
 formula(s,"1/g = ∫₀ᴱc tanh(√(ξ² + Δ²)/(2kBT)) / √(ξ² + Δ²) dξ",4.62,"g = N₀V；这是代码真正使用的归一化。");
}
{
 const s=make("无量纲化：先算形状，再换物理单位","Dimensionless model",
  "定义x=ξ/Ec，d=Δ/Ec，t=kBT/Ec。积分中的Ec抵消，只有g决定无量纲结果。程序temperature是t，不是温度K。给定假设截止Ec后才能做单位换算。本例20meV仅用于教学，未从Al的DFT导出。");
 table(s,[["变量","定义","代码含义"],["x","ξ / Ec","积分变量，范围 0 到 1"],["d","Δ / Ec","gap() 返回值"],["t","kBT / Ec","temperature 参数"],["tc","kBTc / Ec","critical_temperature() 返回值"]]);
 formula(s,"1/g = ∫₀¹ tanh(√(x²+d²)/(2t)) / √(x²+d²) dx",5.16);
}
{
 const s=make("零温解：先拿到一个精确基准","Zero-temperature limit",
  "T=0时tanh变成1，积分为asinh(1/d0)，所以d0=1/sinh(1/g)。这是有限截止模型精确公式。弱耦合才近似为2exp(−1/g)。测试使用独立数值积分验证这一公式，以避免完全同源的自我确认。");
 formula(s,"1/g = asinh(1/d₀)    ⇒    d₀ = 1/sinh(1/g)",2.0);
 rect(s,.65,3.8,5.83,2.43,C.teal);
 text(s,stats.Delta0_over_Ec.toFixed(9),.98,4.15,5.14,.85,{fontFace:"Cambria",fontSize:44,color:C.white});
 text(s,"g = 0.30 的精确有限截止结果",.98,5.26,5.14,.43,{fontSize:18,color:C.white});
 panel(s,"弱耦合近似","g ≪ 1 时 d₀ ≈ 2 exp(−1/g)\n不要用近似值强行替代精确式。",6.84,3.8,5.83,2.43,C.pale);
}
{
 const s=make("Tc：用线性化方程，不用拟合曲线","Critical temperature",
  "让d趋于零得到临界方程。正温度下x=0处核的极限是1/(2tc)，不发散。tc用独立求根得到。弱耦合tc≈2e^γ/π exp(−1/g)，与d0结合得到3.527754。有限g的比值可以稍有偏差，不代表程序错或强耦合理论已实现。");
 formula(s,"1/g = ∫₀¹ tanh(x/2tc)/x dx",2.0,"x → 0 的有限极限为 1/(2tc)");
 panel(s,"弱耦合结果","tc ≈ [2 exp(γ)/π] exp(−1/g)\n2Δ₀/(kBTc) → 3.527754",.65,3.7,5.83,2.62);
 panel(s,"默认有限截止结果","tc = " + stats.kBTc_over_Ec.toFixed(9) + "\n能隙比 = " + stats.gap_ratio.toFixed(6),6.84,3.7,5.83,2.62,C.pale);
}
{
 const s=make("数值算法：括区间求根 + 代回检查","Numerical strategy",
  "quad进行自适应积分，在变化尺度设置分段点。Brent求根需要两端异号。在正温度且低于tc时，正根位于0到d0，Tc以上选择正常态零解。实际程序对d和t用d0缩放求根变量，改善弱耦合精度。极端小g会拒绝，以免把精度失效误判为无超导。");
 steps(s,[["零温","先得到 d₀"],["Tc","R(0,t) = 0"],["扫描","R(d,t) = 0"],["检查","残差与极限"],["保存","CSV + 图 + 版本"]],2.17);
 text(s,"R(d,t) = 积分 − 1/g；T ≥ Tc 不再强求正根。",.8,5.67,11.5,.77,{fontFace:"Cambria Math",fontSize:27,align:"center"});
}
{
 const s=make("把公式对应到代码入口","Code map",
  "先看bcs.py，再跑run_bcs.py，最后读test_bcs.py。model.gap(t)中t为kBT/Ec。可通过README创建虚拟环境，依赖固定了主要数值库版本。Notebook从本例目录启动，避免找不到bcs模块。所有图可以用同一脚本重新生成。");
 table(s,[["入口","计算内容","学习重点"],["BCSModel(g)","明确归一化与容差","不要把 g 当 EPC λ"],["delta0_exact","有限截止零温式","精确值与弱耦合近似"],["critical_temperature()","线性化积分求根","x = 0 的极限"],["gap(t, tc)","非零支路求根","正常态分支与低温平台"],["run_bcs.py / test_bcs.py","生成结果 / 自动检查","不能只有画图，没有验证"]]);
}
{
 const s=make("能隙温度曲线：实线不是拟合","Temperature scan",
  "图片由本仓库run_bcs.py生成，111个温度点，从0到1.10Tc。实线是有限截止方程求解；虚线为常用tanh近似插值。低温平台在浮点精度下可出现相等的相邻点，自动检查是非增而非严格下降。正常态点不参与已除以Δ的残差检查。");
 image(s,"gap_vs_temperature.png",.65,1.93,8.02,4.9);
 panel(s,"读图提示","低温：热激发受抑制\n\nTc 附近：能隙趋于零\n\n虚线：经验插值近似",9.0,2.25,3.67,3.98,C.pale);
}
{
 const s=make("耦合扫描：为什么不是处处 3.53？","Weak-coupling check",
  "g扫描0.18到0.60。弱耦合指数公式在小g时吻合更好，能隙比趋于3.527754。较大g时有限截止偏差增加，但模型仍是同一个静态常DOS平均场，不能称为强耦合Eliashberg。这里的g不等于电子–声子耦合λ。");
 image(s,"coupling_scan.png",.65,1.94,12.02,4.42);
 text(s,"有限截止效应 ≠ 已包含 Eliashberg 强耦合修正。",.8,6.44,11.55,.41,{fontSize:21,color:C.coral,align:"center"});
}
{
 const s=make("态密度 DOS：观测量也有近似","Dynes density of states",
  "图片采用η/Δ0=0.03的Dynes现象学展宽，常DOS低能近似。η不是从杂质散射或第一性原理得到的寿命，也不等于DFT的degauss。展宽降低相干峰并产生隙内权重。DOS公式不施加能隙方程的有限截止，需在低能范围解释。");
 image(s,"dos.png",.65,1.93,8.02,4.9);
 panel(s,"可修改的练习","η/Δ₀ = 0.01、0.03、0.10\n\n比较峰高、宽度与隙内 DOS。\n\nη 只是现象学输入。",9.0,2.25,3.67,3.98,C.pale);
}
{
 const s=make("换单位：9.39 K 不是材料预测","Physical units",
  "固定g=0.30并假设Ec=20meV，Tc=tc*Ec/kB≈9.387945K，Δ0≈1.428778meV。Ec加倍且g不变时两者加倍，无量纲曲线不变。真实材料更改能标可能同时更改DOS和相互作用，不能自动照搬。此数与Al集群测试没有参数关联。");
 formula(s,"Tc [K] = tc × Ec [eV] / kB [eV/K]",2.0);
 panel(s,"假设 Ec = 20 meV","Tc ≈ 9.387945 K\nΔ₀ ≈ 1.428778 meV",.65,3.7,5.83,2.62);
 panel(s,"固定 g，Ec 加倍","K 与 meV 数值加倍\nΔ/Δ₀、T/Tc 曲线不变",6.84,3.7,5.83,2.62,C.pale);
}
{
 const s=make("验证表：从“能运行”到“可信”","Validation",
  "实际7个unittest均通过。此处把7项按5组展示：零温独立积分、弱耦合、趋势与端点、DOS对称正常极限、单位非法输入。默认非零支路最大残差约3.87e−13。容差扫描检查积分稳定性，不能等价于材料k/q网格收敛。");
 table(s,[["检查","默认结果 / 规则","为什么需要"],["自动测试","7 / 7 通过","保护公式、分支与单位"],["零温与弱耦合","独立积分；g=0.18 比值极限","不以经验比值作为输入"],["趋势与端点","非增；T ≥ Tc 返回零","低温平台不能误判"],["非零分支残差","最大约 3.87 × 10⁻¹³","结果必须代回原问题"],["积分容差扫描","10⁻⁶、10⁻⁸、10⁻¹⁰","排除数值容差敏感性"],["DOS 与输入","正常极限、对称性、非法输入","防止漂亮但错误的图"]]);
}
{
 const s=make("三个练习：预测结果，再改参数","Exercises",
  "不要先看答案。练习A把g改为0.18，能隙比应更接近弱耦合值。B固定g把Ec加倍，无量纲曲线不变，物理Tc与Δ0加倍。C把η增大，DOS峰降低并变宽，隙内权重增加。完整教程还有因子2、矩阵对角化练习和答案。");
 steps(s,[["A · 耦合","g：0.30 → 0.18\n比值更接近弱耦合极限？"],["B · 单位","Ec：20 → 40 meV\n哪些量变、哪些不变？"],["C · 展宽","η/Δ₀：0.03 → 0.10\n峰高和隙内权重如何变？"]],2.15);
 text(s,"提交一页解释：参数、预测、结果、差异、误差。",.8,5.85,11.5,.65,{fontSize:25});
}
{
 const s=make("推荐学习顺序：三次完成，不一次硬啃","Study sessions",
  "第一轮只读物理和推导，重点是单自旋DOS、均值分解和自洽。第二轮Notebook逐格运行，先观察结果再改参数。第三轮运行测试并完成独立积分、单位和残差解释。时间是学习安排建议，不是任务自动计时。遇到公式困难时先掌握计算对象和假设，再补二次量子化。");
 steps(s,[["第 1 次","60–90 分钟\n读符号、推导、解析极限"],["第 2 次","60–90 分钟\n逐格运行 Notebook"],["第 3 次","45–60 分钟\n检查误差并完成练习"]],2.15);
 rect(s,.65,5.37,12.02,1.29,C.pale);
 text(s,"Markdown 看细节；PPTX 看结构；Notebook 改参数；脚本重建结果。",
  .95,5.57,11.4,.83,{fontSize:22});
}
{
 const s=make("连接材料：DFT 不直接输出 BCS 能隙","First-principles bridge",
  "常态DFT得到电子结构与电荷密度，DFPT得到晶格响应，EPC才提供电子–声子矩阵元，Eliashberg求配对与重整化。本次仅执行SCF、Γ声子与ASR；定位了epw.x并不等于跑过EPW。非声子路线需另选模型与方法。");
 steps(s,[["DFT","常态电子与基态"],["DFPT","声子和势响应"],["EPC","g、α²F、λ"],["Eliashberg","Δ、Z、Tc"]],2.3);
 text(s,"BCS 的 g ≠ EPC 的 λ；配对 Ec ≠ DFT 的 ecutwfc。",.75,5.68,11.6,.83,{fontSize:24,color:C.coral});
}
{
 const s=make("Al 输入：每个参数都要知道单位","QE input",
  "实际使用fccAl单原子原胞，a=7.65339Bohr约4.05Å，PBE PAW赝势。SCF是40Ry波函数截止、320Ry电荷截止、8³偏移k网格、MV smearing0.02Ry。只是冒烟参数，没有做cutoff/k/smearing收敛。赝势来自集群既有文件，仓库只保存文件名和哈希，不再分发。");
 table(s,[["设置","本例输入","解释"],["结构","ibrav=2，nat=1","fcc 原胞；只有 3 个声子分支"],["晶格","celldm(1)=7.65339","Bohr，不是 Å"],["平面波","40 / 320 Ry","ecutwfc / ecutrho"],["金属积分","8³ 偏移，mv，0.02 Ry","数值占据展宽，不是超导温度"],["声子","q=(0,0,0)","只算 Γ，不是全 q 网格"],["基态关联","相同 prefix / outdir","声子读取对应 SCF 数据"]]);
}
{
 const s=make("真实集群测试：保存任务身份和证据","Cluster evidence",
  "按HostBridge约定使用DirectMCPTaskRunner，计算放Slurm。主Job313274，iq-main，4MPI，8GB，20分钟上限。sacct确认COMPLETED，退出0:0，实际13秒。程序日志SCF5次收敛，总能量−39.50303902Ry，pw和ph均JOBDONE。提交收据不是科学完成证明，要核对应用日志。");
 panel(s,"主任务 JobID 313274","QE 7.5 · iq-main · 4 MPI\nCOMPLETED · ExitCode 0:0\nSCF：5 次迭代\nE = −39.50303902 Ry",.65,2.0,5.83,3.67);
 panel(s,"可追溯证据","输入与提交脚本\noutput / phonon.output\nSlurm 状态快照与完成标记\n赝势 SHA256 与环境版本",6.84,2.0,5.83,3.67,C.pale);
 text(s,"WorkDir: /home/runhan/work_superconductor_bcs_20261003/02_qe_al_smoke",.75,6.16,11.6,.47,{fontSize:15,fontFace:"Consolas"});
}
{
 const s=make("Γ 点的负频率：保留原始值再解释","Acoustic sum rule",
  "原始三个声学频率都是−3.374924cm−1，表示动力学矩阵负本征值的虚频记法。在单原子原胞Γ平移理论应为零。另提交Job313279，单核dynmat，crystalASR后三个频率为0.000000cm−1，COMPLETED0:0。ASR强制平移约束，不代表原始采样已收敛，更不能排除有限q不稳定。");
 panel(s,"原始 ph.x 输出","−3.374924 cm⁻¹\n−3.374924 cm⁻¹\n−3.374924 cm⁻¹\n未施加 ASR，原文件保留",.65,2.05,5.83,3.59);
 panel(s,"crystal ASR 后处理","0.000000 cm⁻¹ × 3\nJobID 313279 已完成\n输出写入新文件\n不覆盖原始动力学矩阵",6.84,2.05,5.83,3.59,C.pale);
 text(s,"满足 Γ 平移约束 ≠ 证明全声子/EPC 网格收敛。",.75,6.12,11.6,.53,{fontSize:23,color:C.coral});
}
{
 const s=make("下一步：收敛测试，不急着宣布 Tc","Convergence roadmap",
  "建议先独立扫描ecutwfc与ecutrho，再联合k网格和smearing，看能量、应力和指定q频率。有限q测试之后才扩展q网格和EPC。每个点用独立目录防止scratch相互覆盖。能量和频率容差要事先写清，最后以λ、α²F、Tc稳定性为目标。这个表是计划，不是已完成结果。");
 table(s,[["层次","建议练习","保存的比较量"],["基组","40 → 50 → 60 Ry；独立 ecutrho","能量 / 原子、应力"],["电子积分","8³ → 12³ → 16³；多档 smearing","EF、能量、频率"],["声子","有限 q → 全 q 网格","色散、原始/ASR 区分"],["EPC","粗网格 → 插值 → 细网格","矩阵元、α²F、λ"],["配对方程","温度、频率截断、μ* 敏感性","Δ、Z、Tc 与误差"]]);
}
{
 const s=make("文献复现：先选一张图或一张表","Reproduction discipline",
  "下一项目可参考EPW官方Pb各向同性或MgB2各向异性超导教程，再选原始论文的明确图表。先记录目标、输入、版本、近似、参数。先跑低成本基准，检查收敛，再逐点比较。只下载资料或跑通软件不等于已复现。不能为了匹配结果任意调μ*而不解释。");
 steps(s,[["明确目标","图号、表号与条件"],["对齐模型","结构、赝势和近似"],["独立计算","保存输入和版本"],["比较误差","逐点差异与原因"]],2.15);
 text(s,"当前状态：教学基准已验证；原论文定量图表复现尚未开始。",.75,5.76,11.6,.83,{fontSize:24,color:C.coral});
}
{
 const s=make("开放教材：可以复用，也要保留许可","Teaching resources",
  "本仓库下载了MITOCW6.763Lecture19和8.514ProblemSet6原始PDF，未修改。TerryP.Orlando与LeonidLevitov授课资料，由MITOpenCourseWare发布，遵守CCBYNCSA4.0：署名、非商业、相同方式共享。归属、原链接、下载日期与SHA256见resources。该许可只说明这两个PDF，不能自动视为全仓库许可。没有复制版权状态不明教材或EPW整套数据。");
 panel(s,"MIT 6.763 · Lecture 19","Terry P. Orlando · 2005\n微观相互作用与声子背景\n原始 PDF，未修改",.65,2.0,5.83,3.18);
 panel(s,"MIT 8.514 · Problem Set 6","Leonid Levitov · 2003\nBCS 准粒子与能隙练习\n原始 PDF，未修改",6.84,2.0,5.83,3.18,C.pale);
 text(s,"CC BY-NC-SA 4.0：署名 · 非商业 · 相同方式共享",.75,5.62,11.6,.55,{fontSize:23,color:C.coral});
 text(s,"原始链接、文件哈希与许可：resources/开放教材与复用说明.md",.75,6.37,11.6,.37,{fontSize:17});
}
{
 const s=make("先完成一个小而完整的学习闭环","Next action",
  "第一项行动是用自己的话解释温度曲线，并重新生成所有图；第二项是完成独立数值检查；第三项阅读Al集群日志，区分正常完成、电子自洽、声子约束和材料收敛。然后进入BdG基准或Al参数收敛。参考：BCS原论文doi10.1103/PhysRev.108.1175；MITOCW课程资源；QE输入官方文档；EPW官方超导教程；HostBridge计算约定。",true);
 text(s,"推导一条公式\n修改一个参数\n解释一项误差",.75,2.06,7.4,2.74,{fontSize:35,color:C.white,paraSpaceAfterPt:14});
 circle(s,9.34,2.24,2.45,C.teal);
 text(s,"1",9.34,2.33,2.45,1.95,{fontFace:"Cambria",fontSize:92,color:C.white,align:"center"});
 text(s,"学习闭环",9.28,5.01,2.66,.49,{fontSize:24,color:C.white,align:"center"});
 text(s,"资料不是终点；能够独立重建、检验和解释，才是下一步。",.75,6.19,11.6,.45,{fontSize:22,color:"A6CECA"});
}

if (pptx._slides.length !== total) throw new Error("Unexpected slide count");
async function writeDeck() {
  const filename = path.join(__dirname, "BCS超导理论与计算入门.pptx");
  await pptx.writeFile({ fileName: filename });
  // Keep per-slide notes and their master relationships, but omit the optional
  // presentation-level list that PptxGenJS 4.0.1 places in the wrong sequence.
  const zip = await JSZip.loadAsync(fs.readFileSync(filename));
  let xml = await zip.file("ppt/presentation.xml").async("string");
  const notes = xml.match(/<p:notesMasterIdLst>[\s\S]*?<\/p:notesMasterIdLst>/);
  if (!notes) throw new Error("Missing notes master");
  xml = xml.replace(notes[0], "");
  zip.file("ppt/presentation.xml", xml);
  fs.writeFileSync(filename, await zip.generateAsync({ type: "nodebuffer" }));
  console.log("Created " + total + " slides with notes: " + filename);
}
writeDeck().catch(error => { console.error(error); process.exitCode = 1; });
